title: Sorftime AI Supply Chain
description: AI-driven cross-border ecommerce intelligence
email: contact@sorftime.com
theme: minima
permalink: /:title/
url: ''
baseurl: ''
lang: en
show_excerpts: true
excerpt_separator: <!--more-->
reading_time: true
