title: Sorftime AI Supply Chain
description: AI-driven cross-border ecommerce intelligence
email: contact@sorftime.com
theme: minima
permalink: /:title/
url: 'https://sorftime-ai-supply-chain.github.io'
baseurl: 'https://sorftime-ai-supply-chain.github.io'
lang: en
show_excerpts: true
excerpt_separator: <!--more-->
reading_time: true
